name: devpop
description: Daily dose of programming wisdom at your fingetips
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Mgmt
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Helpers
  logger: ^2.5.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
